### PR TITLE
Fix missing title page and various small doc corrections.

### PR DESCRIPTION
**Pull request by kerautret**
#312 PR Description

Fix missing title page and various small doc corrections.

# Checklist

- [x] Doxygen documentation of the code completed (classes, methods, types, members...).
- [x] Main tool doxygen documentation (following existing documentation of [DGtalTools documentation](http://dgtal.org/doc/tools/nightly/).
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [x] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Merging this one

**Comment by dcoeurjo** [comment]
I don’t know why but I cannot merge this PR (from the iOS GitHub app). maybe a Travis issue ?

**Comment by kerautret** [comment]
@dcoeurjo thanks yes probably travis is busy I reload it ;)

**Comment by kerautret** [comment]
travis green ;) merging

**Pull request merged**
