### PR TITLE
Check if QGLViewer is enable for 3dCurvatureViewer

### PR DESCRIPTION
**Pull request by jlevallois**
- Check if QGLViewer is enable for 3dCurvatureViewer and 3dCurvatureViewerNoise.
- Can be compile now without QGLViewer (=> export only in Obj/dat without visualisation)

( /ping Issue #207 )

:octocat:

### CODE REVIEW

**Comment by kerautret** [comment]
oups I check the PR perhaps in bad order, sorry, could you please merge from master ?

**Comment by jlevallois** [comment]
It's done :)

:octocat:

**Comment by kerautret** [comment]
Ok thank I look it and could you please add the fix in changelog since it can now work without qglviewer ?

**Comment by kerautret** [comment]
Looks nice, thanks! (export in obj is fine with @dcoeurjo PR (except normals) with PR 980 ... 
I merge.

**Pull request merged**
