### PR TITLE
Support for LambdaMST3DBy2D

### PR DESCRIPTION
**Pull request by copyme**
This PR adds support for L-MSTBy2D tangent estimator into 3dCurveTangentEstimator and needs #1339 from DGtal.

### CODE REVIEW

**Comment by copyme** [comment]
example_lmst_by2d

An example of computing tangent with L-MST3DBy2D for a knot 3_1 curve.

**Comment by dcoeurjo** [comment]
can you please merge back the master ?

**Comment by copyme** [comment]
@dcoeurjo  done

**Comment by kerautret** [comment]
also here, thanks

**Comment by kerautret** [comment]
ping @copyme did you think to have time to have a look on the travis/appveyor issue ?
Or if you prefer we can postpone after 1.0 ? (almost ready the doc is now fixed)

**Comment by copyme** [comment]
@kerautret sure, I will have a look tomorrow

**Comment by copyme** [comment]
@kerautret looking into this...

**Comment by kerautret** [comment]
thanks @copyme 👌, you can take time if you prefer, David plane to send the release begin of next week

**Comment by copyme** [comment]
@kerautret should be fine by now but let's wait for travis.

**Comment by copyme** [comment]
@kerautret by the way can we expose Boost_USE_STATIC_LIBS  in the CMake menu, please? My OS does not provide packages with static libraries of boost and I always have to play with this option.

**Comment by kerautret** [comment]
Thanks,
> @kerautret by the way can we expose Boost_USE_STATIC_LIBS in the CMake menu, please? My OS does not provide packages with static libraries of boost and I always have to play with this option.

do you mean with a ccmake option ?

**Comment by copyme** [comment]
@kerautret yes, exactly.

**Comment by kerautret** [comment]
ok yes I add it

**Comment by kerautret** [comment]
thank 🙏

**Comment by copyme** [comment]
@kerautret there is another fix needed. The interface of LMST3DBy2D changed and needs right now main axis. This main recognition is already in the 3dCurveTangentEstimator but it is not linked with the method. I will have a look at this issue later on today. Sorry for the problem I did forget about the API changes I made before.

**Comment by copyme** [comment]
@kerautret I did not have time. I should have time tomorrow. Sorry, the other code I am working here needed more time than it was planned.

**Comment by copyme** [comment]
@kerautret Unfortunately, this PR will have to wait for another release of DGtalTools. I figured out that a proper implementation will need more work than what I can invest right now. In any case, LMSTBy2D is not very interesting so the importance of this PR is very low. In short, do not wait for this PR. I will finish it later on and keep you posted.

**Comment by kerautret** [comment]
Ok no pb, thanks for the feedback.

**Pull request closed without merging**
