### PR TITLE
Add an options to 3dCurvatureViewer (w/o noise) to output normal vectors.

### PR DESCRIPTION
**Pull request by dcoeurjo**
(based on IntegralInvariant)

### CODE REVIEW

**Comment by kerautret** [comment]
nice feature, thanks!
The normals visualisation is fine, but the export is not working for me. I have only a file with the header.
It is also true for the principal curvature dir, so not related to this PR but by the way if you see the change ;)

**Comment by dcoeurjo** [comment]
I agree. So far the DAT export does nothing.. Let me check with @jlevallois 

BTW, @jlevallois I've slightly changed the parameter names to export OBJ and DAT

**Comment by dcoeurjo** [comment]
@jlevallois can you please have look ?

**Comment by jlevallois** [comment]
Sorry for the delay, I'm working on it

**Comment by jlevallois** [comment]
done in commit b68f81c

:octocat:

**Comment by dcoeurjo** [comment]
cool
merging

**Pull request merged**
