### PR TITLE
Main axis recognition

### PR DESCRIPTION
**Pull request by copyme**
Add an option for showing main axis of a digital point (text and point color if in the viewer mode). The axes are found by checking for a digital point axes of the DSSes passing thru the point.

### CODE REVIEW

**Comment by copyme** [comment]
The point of a stable direction are RED (X), GREEN (Y), BLUE (Z). Then, if a point is not stable e.g., its axes are X and Z then the color of that point is (255,0,255).

image

/cc @JacquesOlivierLachaud

**Comment by copyme** [comment]
The text output looks like this

```
....
[PointVector] {35, 19, 6}|Z MAIN_AXIS = (Z)
[PointVector] {34, 19, 7}|Z MAIN_AXIS = (Z)
[PointVector] {34, 20, 8}|Z MAIN_AXIS = (Z)
[PointVector] {33, 20, 9}|Z MAIN_AXIS = (Z)
[PointVector] {32, 20, 10}|Z MAIN_AXIS = (Z)
[PointVector] {32, 21, 11}|X MAIN_AXIS = (X, Z)
[PointVector] {31, 21, 12}|X MAIN_AXIS = (X, Z)
[PointVector] {30, 21, 13}|X MAIN_AXIS = (X, Z)
[PointVector] {29, 21, 14}|X MAIN_AXIS = (X, Z)
[PointVector] {28, 21, 15}|X MAIN_AXIS = (X, Z)
[PointVector] {27, 22, 15}|X MAIN_AXIS = (X)
[PointVector] {26, 22, 16}|X MAIN_AXIS = (X)
[PointVector] {25, 22, 17}|X MAIN_AXIS = (X)
[PointVector] {24, 22, 17}|X MAIN_AXIS = (X)
[PointVector] {23, 21, 18}|X MAIN_AXIS = (X)
....
```

**Comment by dcoeurjo** [comment]
can you please merge back the master ?

**Comment by dcoeurjo** [comment]
Changelog entry ?

**Comment by copyme** [comment]
@dcoeurjo  done

**Comment by kerautret** [comment]
Thanks  @copyme , I just fix the conflict if @dcoeurjo  is ok we can merge for being in 1.0 ;) 🎉

**Comment by copyme** [comment]
@kerautret cool :-)

**Pull request merged**
