### PR TITLE
New tool: mesh2heightfield

### PR DESCRIPTION
**Pull request by kerautret**
In the same spirit than vol2heightfield it is an adaptation to obtain height map from a mesh.
It could be more efficient but for now it allows it allows to obtain nice height map and mesh normals useful for simple rendering.
tmp

### CODE REVIEW

**Comment by dcoeurjo** [comment]
@kerautret can you please check travis so that I can review this PR?

**Comment by kerautret** [comment]
yes i look it thanks

**Comment by kerautret** [comment]
travis is fine after reload (perhaps a previous DGTal PR merge was needed )

**Comment by dcoeurjo** [comment]
Looking this tool is very specific.. maybe we should consider to move it to "contrib" if we create this repo..

**Comment by dcoeurjo** [comment]
I have a namespace issue:

Users/davidcoeurjolly/Sources/DGtalTools/estimators/generic3dNormalEstimators.cpp:369:11: error: use of undeclared identifier
      'ShapeGeometricFunctors'; did you mean 'DGtal::functors::ShapeGeometricFunctors'?
  typedef ShapeGeometricFunctors::ShapeNormalVectorFunctor<ImplicitShape> NormalFunctor;
          ^~~~~~~~~~~~~~~~~~~~~~
          DGtal::functors::ShapeGeometricFunctors
/Users/davidcoeurjolly/Sources/DGtal/src/DGtal/shapes/ShapeGeometricFunctors.h:52:13: note:
      'DGtal::functors::ShapeGeometricFunctors' declared here
  namespace ShapeGeometricFunctors

**Comment by kerautret** [comment]
yes a little specific, perhaps a first prog for contrib ;)

**Comment by kerautret** [comment]
I look it perhaps just from recent dgtal update

**Comment by kerautret** [comment]
@dcoeurjo for the issue, are you sure that you are on the good branch ? Because it is corrected:
see line 369:  https://github.com/kerautret/DGtalTools/blob/mesh2HeightField/estimators/generic3dNormalEstimators.cpp

**Comment by dcoeurjo** [comment]
ok sorry, my bad :smile: 
merging

**Pull request merged**
