### PR TITLE
Qt5 integration

### PR DESCRIPTION
**Pull request by naubry**
Here are some changes for the support of QT5 in DGtalTools (with DGtal compiled with support of Qt5).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Thanks @naubry. Similarly to the PR in DGtal, could you please help us cleaning up the tools and remove all includes related to qapplication?
Thanks

**Comment by naubry** [comment]
Yes, I will do that tomorrow.

**Comment by kerautret** [comment]
@naubry could you please update from master and by this way reload travis ?

**Comment by kerautret** [comment]
@naubry have you the same pb without ITK ?

**Comment by naubry** [comment]
Before pushing the last modification, I compiled all tools without problems. I haven't ITK on my computer...

**Comment by kerautret** [comment]
The problem is also related to QT4,( it breaks the compilation since the master is fine with current DGtal.)
I don't see the pb, could you install itk from brew ?
The error is something:
Undefined symbols for architecture x86_64:
  "vtable for MainWindow", referenced from:
      MainWindow::MainWindow(DGtal::Viewer3D<DGtal::SpaceND<3u, int>, DGtal::KhalimskySpaceND<3u, int> >*, DGtal::ImageContainerBySTLVector<DGtal::HyperRectDomain<DGtal::SpaceND<3u, int> >, unsigned char>*, QWidget*, QFlags<Qt::WindowType>) in sliceViewer.cpp.o
      MainWindow::~MainWindow() in sliceViewer.cpp.o
      MainWindow::~MainWindow() in sliceViewer.cpp.o
      non-virtual thunk to MainWindow::~MainWindow() in sliceViewer.cpp.o
      MainWindow::~MainWindow() in sliceViewer.cpp.o
      non-virtual thunk to MainWindow::~MainWindow() in sliceViewer.cpp.o
      _main in sliceViewer.cpp.o
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [visualisation/sliceViewer] Error 1
make[2]: *** [visualisation/CMakeFiles/sliceViewer.dir/all] Error 2
make[1]: *** [visualisation/CMakeFiles/sliceViewer.dir/rule] Error 2
make: *** [sliceViewer] Error 2

**Comment by kerautret** [comment]
Perfect ! Now it is fine thanks! I merge

**Pull request merged**
