### PR TITLE
Renaming ShapeGenerator to generators

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

this PR renames shapeGenerator folder to generators (doc updated)

# Checklist

- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [ ] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by kerautret** [comment]
good idea the renaming thanks.
Are the link ok for you ? For me not, I look to it but perhaps it is due to duplicated files with oxygen I was having bad bug about it...
capture d ecran 2016-05-24 a 23 03 54

**Comment by kerautret** [comment]
@dcoeurjo I fix it and I PR on you branch ;)

**Comment by dcoeurjo** [comment]
thanks a lot!
sorry for my delay.. I'm a bit swamped..

**Comment by dcoeurjo** [comment]
Fine merging I guess.. thanks again @kerautret

**Pull request merged**
