### PR TITLE
Fixing 3dLocalEstimator

### PR DESCRIPTION
**Pull request by jlevallois**
Fixing Issue https://github.com/DGtal-team/DGtalTools/issues/202
Fixing Issue https://github.com/DGtal-team/DGtalTools/issues/190

:octocat:

### CODE REVIEW

**Comment by kerautret** [comment]
I try it but I have a lot of errors (not related to your edit), @dcoeurjo I use brew to install cgal and trying to compile DGtalsTools I have these issues:
Scanning dependencies of target 3dLocalEstimators
[100%] Building CXX object estimators/CMakeFiles/3dLocalEstimators.dir/3dLocalEstimators.cpp.o
In file included from /Users/kerautre/EnCours/DGtalTools/estimators/3dLocalEstimators.cpp:37:
In file included from /Users/kerautre/EnCours/DGtal/src/DGtal/helpers/StdDefs.h:46:
In file included from /Users/kerautre/EnCours/DGtal/src/DGtal/kernel/SpaceND.h:48:
/Users/kerautre/EnCours/DGtal/src/DGtal/kernel/PointVector.h:233:23: error: no type
      named 'initializer_list' in namespace 'std'
    PointVector( std::initializer_list<Component> init );
                 ~~~~~^

Have you the same David ?

**Comment by dcoeurjo** [comment]
It seems that cpp11 flag is missing. Can you check the CMakeFiles/flags ?

**Comment by kerautret** [comment]
Yes you are right, perhaps it could be automatically set when selecting CGal in DGTal ?

**Comment by kerautret** [comment]
So it looks to work, I merge but by the way @jlevallois  I  add an issue about the shape option which could more detailed in the helper (like the generic3dNormalEstimators do for the polynomial options).

**Comment by kerautret** [comment]
@jlevallois thanks for the fix!

**Pull request merged**
