### PR TITLE
Doxygen system added to DGtaltools

### PR DESCRIPTION
**Pull request by dcoeurjo**
# PR Description

This PR adds doxygen scripts to DGtalTools. More precisely, doxygen and cmake scripts define a new ```make doc``` target to generate the tool documentation.

Few comments:
- the main page is in ```doc/mainpage.dox```
- only vol2obj tool doc has been added. For this tool, the doc is rather simple (just a copy of the --help).

# TODO
- [x] create a specific CSS/HTML template to distinguish DGtal from DGtalTools doc 
- [ ] use travis to generate the doc as for DGtal
- [ ] make sure that DGtal doc can refer to tools (with proper link)
- [x] add more info to the main page 
- [x] Details Converters section tools
- [x] Details Estimators section tools
- [x] Details ShapeGenerator section tools  
- [x] Details Visualization section tools  
- [x] Details Volumetric section tools  

# Checklist

- [x] Doxygen documentation of the code completed (classes, methods, types, members...)
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [x] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
ping @JacquesOlivierLachaud & @kerautret

**Comment by kerautret** [comment]
Yes thanks I look it this afternoon

**Comment by kerautret** [comment]
@dcoeurjo done for the custom style doc (in PR in your branch), I continue with the add of info

**Comment by kerautret** [comment]
@dcoeurjo done for Converters sections tools (see PR on your branch)
Starting doing smaller one ShapeGenerator ;)

**Comment by kerautret** [comment]
@dcoeurjo done for ShapeGenerator sections tools (see PR on your branch)
Starting doing Visualization ;)

**Comment by kerautret** [comment]
@dcoeurjo done forVisualization sections tools (see PR on your branch)
Starting doing Visualization ;)

**Comment by kerautret** [comment]
@dcoeurjo done for Volumetric sections tools (see PR on your branch)
Starting doing the last one with Estimators ;)

**Comment by dcoeurjo** [comment]
Excellent. I ll prepare the script so that Travis can push the doc. Thanks a lot

**Comment by dcoeurjo** [comment]
can you reopen the PR to my branch ?

**Comment by kerautret** [comment]
done, but it was not closed so I close and re open ;)

**Comment by kerautret** [comment]
@dcoeurjo done for the last one (Estimators)! 
By the way I have corrected minor issue for some tools and add some options for some one in order to have good visual examples.

**Comment by dcoeurjo** [comment]
@kerautret I'll merge this branch in order to debug the deployment of the documentation when a PR is merged.

**Pull request merged**
