### PR TITLE
Cpp17 and Windows GitHub Action 

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description
As done for DGtal, it also integrate GitAction configuration for windows architecture and removes appveyor check.

# Checklist

- [x] Doxygen documentation of the code completed (classes, methods, types, members...).
- [x] Main tool doxygen documentation (following existing documentation of [DGtalTools documentation](http://dgtal.org/doc/tools/nightly/).
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [x] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [x] All continuous integration tests pass (Github Actions & appveyor).

### CODE REVIEW

**Comment by kerautret** [comment]
@dcoeurjo looks ready for review now ;) By the way could you remove the appveyor trigger on the settings ?

**Comment by kerautret** [comment]
ping @dcoeurjo if you have time to remove appveyor in the setting ;)

**Comment by dcoeurjo** [comment]
I think I've removed appveyor...

**Comment by dcoeurjo** [comment]
Seems to still be there... maybe just remove the appveryor.yaml

**Comment by kerautret** [comment]
> I think I've removed appveyor...

thanks, 

> Seems to still be there... maybe just remove the appveryor.yaml

yes but it is well removed in the PR, perhaps I have to make a new commit (but needs conan fix of DGTal PR)

**Comment by kerautret** [comment]
Thanks @dcoeurjo looks fine now ;)

**Review by dcoeurjo — APPROVED** [review]
Excellent! Thx

**Pull request merged**
