### PR TITLE
Add thinning based on Critical Kernels

### PR DESCRIPTION
**Pull request by phcerdan**
# PR Description
Application to use the thinning based on critical kernels. Associated to [DGtal PR:1147](https://github.com/DGtal-team/DGtal/pull/1147)

# Checklist

- [x] Doxygen documentation of the code completed (classes, methods, types, members...).
- [x] Main tool doxygen documentation (following existing documentation of [DGtalTools documentation](http://dgtal.org/doc/tools/nightly/).
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [x] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by phcerdan** [comment]
Have a look at the Readme in my branch for a screenshot: https://github.com/phcerdan/DGtalTools/tree/thin_criticalkernel

**Comment by kerautret** [comment]
@phcerdan since It depends of the DGtal PR, we can perhaps wait for the next milestone ?

**Comment by phcerdan** [comment]
@kerautret the [VoxelComplex PR](https://github.com/DGtal-team/DGtal/pull/1147) has been merged in DGtal for release 0.9.4

**Comment by phcerdan** [comment]
In fact, I refer to this script in the DGtal docs, so, it would be a nice thing to have it at the same time.

**Comment by dcoeurjo** [comment]
Allgood merging. Thanks

**Pull request merged**
