### PR TITLE
Variant of discrete Ambrosio-Tortorelli

### PR DESCRIPTION
**Pull request by JacquesOlivierLachaud**
# PR Description

This PR adds another variant for the discrete calculus model of Ambrosio-Tortorelli functional. This variant uses the Laplacian instead of the gradient of the singularity function to estimate the length of discontinuities.

# Checklist

- [X] Doxygen documentation of the code completed (classes, methods, types, members...).
- [x] Main tool doxygen documentation (following existing documentation of [DGtalTools documentation](http://dgtal.org/doc/tools/nightly/).
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [x] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
;) Nice. 
Elie’s trick ?

**Comment by JacquesOlivierLachaud** [comment]
Yes, following his talk. I have to do more tests to see if its useful theoretically (correct H1 estimation) and practically. For now, results look very similar (and slower to compute  :-( )

**Comment by dcoeurjo** [comment]
Can this PR be reviewed ?

**Comment by dcoeurjo** [comment]
could you please update the changelog ?

**Comment by JacquesOlivierLachaud** [comment]
I am on it. I am currently checking the doc.

**Comment by JacquesOlivierLachaud** [comment]
All done ! Thanks

**Pull request merged**
