### PR TITLE
Add const directives to some curve estimator on shapes

### PR DESCRIPTION
**Pull request by akrah**
# PR Description

Changes to take into account the [DGtal PR #1429](https://github.com/DGtal-team/DGtal/pull/1429) with the same name, that consists in simplifying and homogenizing the use of curve estimators on shapes.

# Checklist

- [x] Doxygen documentation of the code completed (classes, methods, types, members...).
- [x] Main tool doxygen documentation (following existing documentation of [DGtalTools documentation](http://dgtal.org/doc/tools/nightly/).
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [ ] Update the readme with potentially a screenshot of the tools if it applies. 
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by kerautret** [comment]
Sorry @akrah I miss the PR, could you please check the appveyor/travis issue ?

**Comment by akrah** [comment]
Sorry @kerautret, I missed the reply ;).
Actually this PR will only be valid when the DGtal PR #1429](https://github.com/DGtal-team/DGtal/pull/1429) will be merged into the master branch. I will re-run the tests after the merge.

**Comment by kerautret** [comment]
> Sorry @kerautret, I missed the reply ;).
> Actually this PR will only be valid when the DGtal PR #1429]([DGtal-team/DGtal#1429](https://github.com/DGtal-team/DGtal/pull/1429)) will be merged into the master branch. I will re-run the tests after the merge.

@akrah ok I see no pb, ping me when it is fine.

**Comment by kerautret** [comment]
@akrah to solve the conflict I have PR on your branch a merge: https://github.com/akrah/DGtalTools/pull/1
Can you check and merge and by the way put remove circulator waiting for the check of difference ?

**Comment by dcoeurjo** [comment]
Hi @akrah , could you please have a look to @kerautret 's PR ? I'm waiting for the issue to be solved before releasing DGtal.
thx

**Comment by akrah** [comment]
Hi @kerautret @dcoeurjo,
I merged the kerautret's PR. I think that if the DGtal PR have also been merged, we don't need to change circulators, what do you think?

**Comment by dcoeurjo** [comment]
In DGtal, the const stuff has been merged into the rel1.1 branch. We may have a deadlock here ;) Let's merge this one and see where we are.
Stay tuned in case we need to quickly fix the master;)

**Pull request merged**
