### PR TITLE
fix bug reading option in volCComponentCounter

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description

Fix bug reading option in volCComponentCounter

# Checklist

- [n.a] Doxygen documentation of the code completed (classes, methods, types, members...)
- [n.a] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [n.a] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
fine for me. What was the bug you have with this tool ?

**Comment by kerautret** [comment]
The count of Connected components looks not always good: for instance try :
[bugCCCounter.vol.zip](https://github.com/DGtal-team/DGtalTools/files/181004/bugCCCounter.vol.zip)
it produce 4 cc while it looks to be 3.

**Comment by kerautret** [comment]
@dcoeurjo perhaps I add an issue for the fix and assign to you ? ;)

**Comment by dcoeurjo** [comment]
Yes, please do so

**Comment by kerautret** [comment]
done https://github.com/DGtal-team/DGtalTools/issues/255
So merging thanks ;à

**Pull request merged**
