### PR TITLE
DGtalTools on MS Windows

### PR DESCRIPTION
**Pull request by kerautret**
as the PR of DGTal: (https://github.com/DGtal-team/DGtal/pull/1074)
It is also ready with appveyor check ;à) !

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Fantastic !! Would you have a snapshot with qglviewer? Just curious...
can you please have a look the the appeveyor I'm DGtal ?

**Comment by kerautret** [comment]
yes, It could be greats with QGLviewer, it seems that we have qt4/5 on the virtual machine so perhaps it is possible, I will try

**Comment by kerautret** [comment]
yes the PR I look it

**Comment by kerautret** [comment]
@dcoeurjo now I have QGLviewer on appveyor, it looks that it implies other warnings or error (not fatal) but I look it in a new DGtal PR in complement to MSBuild ...

**Comment by kerautret** [comment]
@dcoeurjo yes... that work on MS with QGLviewer activated ! 
(with DGtal PR #1106)

**Comment by dcoeurjo** [comment]
cool ;) 
would you have a snapshot?

**Comment by kerautret** [comment]
yes, it remains some warnings but no more errors ;) 
capture d ecran 2016-01-11 a 13 41 09

**Comment by dcoeurjo** [comment]
;) I meant a snapshot of the viewer for instance in MS..

**Comment by kerautret** [comment]
I have not yet it, but soon ;)

**Pull request merged**
