### PR TITLE
heightfield2shading

### PR DESCRIPTION
**Pull request by kerautret**
Tool to apply simple rendering from hightfield and normals vector field.
For now you can apply lambertian and specular (Nayar model) reflectance map.
Combined with the mesh2heightfield you can obtain such visus:
shading

capture d ecran 2015-04-13 a 14 51 39

### CODE REVIEW

**Comment by kerautret** [comment]
Now you can also have another light model from its position wich emits in all directions:
capture d ecran 2015-04-16 a 12 30 23

**Comment by kerautret** [comment]
add also a rendering from normal mapping:
capture d ecran 2015-04-16 a 15 30 33

**Comment by kerautret** [comment]
obtained with this bitmap:
capture d ecran 2015-04-16 a 13 55 22

**Comment by dcoeurjo** [comment]
Ok for this tool, I'll merge it. However, maybe it could be moved to "3rdParty" tools if we create this project.

**Pull request merged**
