### PR TITLE
Slice viewer color map

### PR DESCRIPTION
**Pull request by kerautret**
Address issus #188
Now we can have such display by using args:
./visualisation/sliceViewer -i ../../DGtal/examples/samples/lobster.vol --gradHotColorMap
capture d ecran 2015-04-21 a 23 44 06
 (note that for RandomColorMap I had some issues to include it in the main functor).
Also another limit was the non possible use of template inside QWindow so  the use of gradientColorMap is not easy with its template parameter on type of map. ;(

### CODE REVIEW

**Comment by dcoeurjo** [comment]
sorry for the delay..
On my system (up-to-date mac+boost), I have a strange issue:

       [ 80%] Generating moc_sliceViewer.cxx
       usr/local/Cellar/boost/1.58.0/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"

**Comment by dcoeurjo** [comment]
(I understand the template stuff but that would have been nice to be able to switch colormaps without restarting the app)

**Comment by dcoeurjo** [comment]
I still have this BOOST_JOIN issue.. any iddea?

**Comment by kerautret** [comment]
I have the 0.57 ;) I update it...

**Comment by kerautret** [comment]
It compile fine for me... (also with 0.58 of boost and last release of el captain xCode 7 with command line tools and qt5...)

**Comment by kerautret** [comment]
@dcoeurjo you are with QT4 ?

**Comment by dcoeurjo** [comment]
Yep I have QT4 and I still have the bug

**Comment by kerautret** [comment]
and here ? (on the branch  SliceViewerColorMapBOOSTfix ?)

**Comment by kerautret** [comment]
I try to add also the button to switch color map

**Comment by kerautret** [comment]
@dcoeurjo  that works for the button to change the color map ;)
Hope that the boost bug is fixed with these commits...

**Comment by dcoeurjo** [comment]
okay.. no more boost issue (thanks for the fix) and the colormap selector is great ;)

But, I have an issue when changing the zoom: only a quater of the image is displayed: 
capture d ecran 2015-10-03 a 14 38 10

**Comment by kerautret** [comment]
ok, good for the boost fix ;) 
For the display it should be bug for not 0 centered image of BasicDomainSubSampler of DGtal, I look it for a fix..

**Comment by dcoeurjo** [comment]
BTW would it be possible to have the rotation center in the 3D view on  the object center ?

**Comment by kerautret** [comment]
ok yes, the bug its simpler, it is fine, I add the center rotation.

**Comment by kerautret** [comment]
@dcoeurjo all done

**Comment by dcoeurjo** [comment]
Perfect !! thanks, merging.

**Pull request merged**
