### PR TITLE
Random build

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description
Following the @dcoeurjo DGtal [PR 1588](https://github.com/DGtal-team/DGtal/pull/1588), it implements a random build with also and explicit whithelist. Typical use:
`cmake .. -DDGTALTOOLS_RANDOMIZED_BUILD_THRESHOLD=25  -DDGTALTOOLS_RANDOMIZED_BUILD_WHITELIST="$(cat ../cmake/whiteListBuildTools.txt)"`

# Checklist

- [ ] Doxygen documentation of the code completed (classes, methods, types, members...).
- [ ] Main tool doxygen documentation (following existing documentation of [DGtalTools documentation](http://dgtal.org/doc/tools/nightly/).
- [ ] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [ ] Update the readme with potentially a screenshot of the tools if it applies. 
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Why did you use a white list in txt rather than the direct shell script as in DGtal ?
Is the script not working ?
(Just curious)

**Comment by kerautret** [comment]
> Why did you use a white list in txt rather than the direct shell script as in DGtal ?
> Is the script not working ?
> (Just curious)
In fact, I first add a static list in link to the use through the DGTal Travis build when no tools will be changed. But sure the script perfectly works and also useful for the travis DGtalTools itself. I add it.

**Comment by kerautret** [comment]
@dcoeurjo I added the script and add the option in travis and appveyor but I miss the change to re activate travis as you done for DGtal, is it in the setting project ? (I have not the hand on it).

**Comment by dcoeurjo** [comment]
I don't know exactly why but I don't have build credits anymore on Travis on my account. 
That may be the problem

**Review by dcoeurjo — APPROVED** [review]
Great 👍

**Pull request merged**
