### PR TITLE
Fix issue #382 (3dLocalEstimators)

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description

Work in progress: 
   - [x] ConstAlias related error
   - [x] __ bind error:

Capture d’écran 2020-06-14 à 19 11 27

# Checklist

- [x] Doxygen documentation of the code completed (classes, methods, types, members...).
- [x] Main tool doxygen documentation (following existing documentation of [DGtalTools documentation](http://dgtal.org/doc/tools/nightly/).
- [x] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools/blob/master/CONTRIBUTING.md)
- [x] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools/blob/master/ChangeLog.md) added.
- [x] Update the readme with potentially a screenshot of the tools if it applies. 
- [x] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).

### CODE REVIEW

**Comment by kerautret** [comment]
Capture d’écran 2020-06-14 à 21 23 50

**Comment by dcoeurjo** [comment]
👌

**Comment by kerautret** [comment]
perhaps related to the version of CGAL ? I use the last one but I can try to change it with the previous one

**Comment by rolanddenis** [comment]
Ok, after my comment in the issue (https://github.com/DGtal-team/DGtalTools/issues/382#issuecomment-643983413), I confirm that this conversion issue comes from the stricter rules in implicit conversions for `PointVector`: the metric accepts integer coordinates while the embedder returns double coordinates.

**Comment by kerautret** [comment]
thanks @rolanddenis you are right, the CanonicSCellEmbedder returns by definition a RealPoint:    
https://github.com/kerautret/DGtalTools/blob/4df1f717b7d844ce6df085d2253f58938b6c87ab/estimators/3dLocalEstimators.cpp#L501-L502
Not sure to see the better alternative, perhaps if @dcoeurjo could see.

**Comment by kerautret** [comment]
@dcoeurjo fixed, I follow the testMonge of DGtal, if you have time to review it is ready ;)

**Comment by dcoeurjo** [comment]
I’m on it ;(

**Comment by dcoeurjo** [comment]
👌merging

**Pull request merged**
